name: Update Release Notes
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_RELEASE_NOTES_TOKEN }}

    steps:

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          ignorePreReleases: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                    "title": "## â• New",
                    "labels": ["new"]
                },
                {
                    "title": "## âŒ Removed",
                    "labels": ["removed", "deleted", "rem", "del"]
                },
                {
                    "title": "## âœ… Bugfixes",
                    "labels": ["fix", "bug", "bugfix",]
                },
                {
                    "title": "## ğŸ’€ Deprecated",
                    "labels": ["deprecated", "depr"]
                },
                {
                    "title": "## ğŸ“¦ Dependencies",
                    "labels": ["dependencies", "dep"]
                },
                {
                    "title": "## âœï¸ Changes",
                    "labels": ["change"]
                },
                {
                    "title": "## ğŸ“ Documentation",
                    "labels": ["docs", "documentation"]
                },
                {
                    "title": "## ğŸ§ª Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## ğŸ¨ UI",
                    "labels": ["ui", "design"]
                },
                {
                    "title": "## âš™ï¸ Build",
                    "labels": ["build", "ci", "cd"]
                },
                {
                    "title": "## Others",
                    "labels": [""]
                }
              ]
            }

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}